version: '3.1'

services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: jpress
       MYSQL_USER: jpress
       MYSQL_PASSWORD: jpress
    ports:
      - "3306:3306"

  jpress:
    depends_on:
      - db
    image: fuhai/jpress:latest
    ports:
      - "80:8080"
      - "443:443"
    restart: always


